version: '3.7'

services: 
  bestxclient:
    build:
      context: ./client
      target: dev
    container_name: bestxclient
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    networks:
      - bestxnet

  bestxserver:
    build:
      context: ./server
      target: dev
    container_name: bestxserver
    environment:
      - NODE_ENV=development
    ports:
      - 8081:8081
    networks:
      - bestxnet
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: bestxdb
    volumes:
      - ./bextxdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d bestxdb'"]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bestxdb
    ports:
      - "6500:5432"
    networks:
      - bestxnet

  adminer:
    image: adminer
    restart: always
    networks:
      - bestxnet
    ports:
      - 8083:8080

volumes:
  bextxdb: 
    name: bestxdb
    driver: local

networks:
  bestxnet:
    driver: bridge